Repository nextcloud/android-library, pull requests merged in 2018-12, with the labels that each got.

#203 Bump parceler 1.1.11 to 1.1.12
  build.gradle
Labels: dependencies

#202 Capability for DirectEditing
  src/com/owncloud/android/lib/resources/status/GetRemoteCapabilitiesOperation.java
  src/com/owncloud/android/lib/resources/status/OCCapability.java
Labels: 2. to review

#204 Add note to file listing
  src/com/owncloud/android/lib/common/network/WebdavEntry.java
  src/com/owncloud/android/lib/common/network/WebdavUtils.java
  src/com/owncloud/android/lib/resources/files/ReadRemoteFolderOperation.java
  src/com/owncloud/android/lib/resources/files/RemoteFile.java
Labels: 2. to review

#206 Analytics: show correct 0 instead of nothing
  scripts/analysis/analysis-wrapper.sh
Labels: 2. to review

#210 Add check for template support
  src/com/owncloud/android/lib/resources/status/GetRemoteCapabilitiesOperation.java
  src/com/owncloud/android/lib/resources/status/OCCapability.java
Labels: 2. to review, backport-request

#213 Fix wrong check for direct editing
  src/com/owncloud/android/lib/resources/status/GetRemoteCapabilitiesOperation.java
  src/com/owncloud/android/lib/resources/status/OCCapability.java
Labels: 2. to review, backport-request
