Repository nextcloud/android-library, pull requests merged in 2019-09, with the labels that each got.

#334 add support for remote wipe
  src/main/java/com/owncloud/android/lib/resources/status/OwnCloudVersion.java
  src/main/java/com/owncloud/android/lib/resources/users/CheckRemoteWipeRemoteOperation.java
  src/main/java/com/owncloud/android/lib/resources/users/RemoteWipeSuccessRemoteOperation.java
Labels: 2. to review, backport-request

#267 Reactivate tests second try
  build.gradle
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/androidTest/java/com/owncloud/android/CopyFileIT.java
  src/androidTest/java/com/owncloud/android/CreateFolderIT.java
  src/androidTest/java/com/owncloud/android/DeleteFileTest.java
  src/androidTest/java/com/owncloud/android/ExceptionParserIT.java
  src/androidTest/java/com/owncloud/android/FileIT.java
  src/androidTest/java/com/owncloud/android/GetCapabilitiesTest.java
  src/androidTest/java/com/owncloud/android/OwnCloudClientManagerFactoryTest.java
  src/androidTest/java/com/owncloud/android/lib/common/operations/CreateShareTest.java
  src/androidTest/java/com/owncloud/android/lib/common/operations/GetSharesTest.java
  src/androidTest/java/com/owncloud/android/lib/common/operations/GetUserQuotaTest.java
  src/androidTest/java/com/owncloud/android/lib/common/operations/RemoveShareTest.java
  src/androidTest/oldTests/CopyFileTest.java
  src/androidTest/oldTests/CreateFolderTest.java
  src/androidTest/oldTests/CreateShareTest.java
  src/androidTest/oldTests/DeleteFileTest.java
  src/androidTest/oldTests/DownloadFileTest.java
  src/androidTest/oldTests/GetCapabilitiesTest.java
  src/androidTest/oldTests/GetShareesTest.java
  src/androidTest/oldTests/GetSharesTest.java
  src/androidTest/oldTests/MoveFileTest.java
  src/androidTest/oldTests/OwnCloudClientManagerFactoryTest.java
  src/androidTest/oldTests/OwnCloudClientTest.java
  src/androidTest/oldTests/ReadFileTest.java
  src/androidTest/oldTests/ReadFolderTest.java
  src/androidTest/oldTests/RemoteTest.java
  src/androidTest/oldTests/RemoveShareTest.java
  src/androidTest/oldTests/RenameFileTest.java
  src/androidTest/oldTests/SelfSignedConfidentSslSocketFactory.java
  src/androidTest/oldTests/SimpleFactoryManagerTest.java
  src/androidTest/oldTests/SingleSessionManagerTest.java
  src/androidTest/oldTests/TestActivity.java
  src/androidTest/oldTests/UpdatePrivateShareTest.java
  src/androidTest/oldTests/UpdatePublicShareTest.java
  src/androidTest/oldTests/UploadFileTest.java
  src/androidTest/oldTests/Utils.java
  src/main/java/com/owncloud/android/lib/resources/files/UploadFileRemoteOperation.java
  src/test/java/com/owncloud/android/lib/resources/files/ChunkedFileUploadRemoteOperationTest.java
  test_client/build.gradle
Labels: 1. developing

#338 Defensive check for Log_OC arguments for null
  src/main/java/com/owncloud/android/lib/common/utils/Log_OC.java
Labels: 2. to review

#339 Add test for get user info
  .drone.yml
  build.gradle
  src/androidTest/kotlin/com/nextcloud/lib/resources/users/GetUserInfoRemoteOperationTest.kt
  src/main/java/com/owncloud/android/lib/common/Quota.java
Labels: 2. to review
