Repository nextcloud/android-library, pull requests merged in 2020-09, with the labels that each got.

#496 use retryRule = 1 for local tests and only 5 for CI
  .drone.yml
  src/androidTest/java/com/owncloud/android/RetryTestRule.kt
Labels: 2. to review

#497 use plain userId for search
  .drone.yml
  src/androidTest/java/com/owncloud/android/lib/resources/files/SearchRemoteOperationTest.java
  src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
  src/main/java/com/owncloud/android/lib/common/utils/WebDavFileUtils.java
  src/main/java/com/owncloud/android/lib/resources/files/SearchRemoteOperation.java
Labels: 3. to release, backport-request

#502 Make it possible to leave upload retries enabled
  src/main/java/com/owncloud/android/lib/resources/files/ChunkedFileUploadRemoteOperation.java
  src/main/java/com/owncloud/android/lib/resources/files/UploadFileRemoteOperation.java
Labels: 2. to review

#503 prefer IPV6 addresses if available
  src/main/java/com/nextcloud/common/IPV6PreferringDNS.java
  src/main/java/com/nextcloud/common/NextcloudClient.kt
  src/main/java/com/owncloud/android/lib/common/network/AdvancedSslSocketFactory.java
Labels: 2. to review

#504 Update sharing part
  src/androidTest/java/com/owncloud/android/FileIT.java
  src/androidTest/java/com/owncloud/android/lib/resources/shares/GetSharesRemoteOperationTest.java
  src/main/java/com/owncloud/android/lib/resources/shares/CreateShareRemoteOperation.java
  src/main/java/com/owncloud/android/lib/resources/shares/OCShare.java
  src/main/java/com/owncloud/android/lib/resources/shares/ShareType.java
  src/main/java/com/owncloud/android/lib/resources/shares/UpdateShareRemoteOperation.java
  src/main/java/com/owncloud/android/lib/resources/status/OwnCloudVersion.java
Labels: 3. to release

#511 auto approve all dependabot
  .github/workflows/autoApproveDependabot.yml
Labels: 2. to review
