Repository nextcloud/android-library, pull requests merged in 2020-12, with the labels that each got.

#553 Plugin 'kotlin-android-extensions' deprecated
  build.gradle
Labels: 2. to review

#561 Remove snapshot repo
  build.gradle
Labels: 2. to review, backport-request

#551 Use NC specific user agent
  src/main/java/com/owncloud/android/lib/resources/notifications/RegisterAccountDeviceForProxyOperation.java
Labels: 2. to review, backport-request, client change required
