Repository nextcloud/android-library, pull requests merged in 2020-07, with the labels that each got.

#461 Edit label for public share
  src/main/java/com/owncloud/android/lib/resources/shares/OCShare.java
  src/main/java/com/owncloud/android/lib/resources/shares/ShareXMLParser.java
  src/main/java/com/owncloud/android/lib/resources/shares/UpdateShareRemoteOperation.java
Labels: 2. to review

#463 remove fileDrop capability
  src/main/java/com/owncloud/android/lib/resources/status/GetCapabilitiesRemoteOperation.java
  src/main/java/com/owncloud/android/lib/resources/status/OCCapability.java
Labels: 2. to review, client change required

#464 Process element color theming values
  src/main/java/com/owncloud/android/lib/resources/status/GetCapabilitiesRemoteOperation.java
  src/main/java/com/owncloud/android/lib/resources/status/OCCapability.java
Labels: 2. to review

#468 unlock after modifying metadata
  src/androidTest/java/com/owncloud/android/lib/resources/e2ee/UpdateMetadataRemoteOperationTest.java
Labels: 2. to review

#465 Add capability via NextcloudClient
  .drone.yml
  src/androidTest/java/com/owncloud/android/GetCapabilitiesTest.java
  src/androidTest/java/com/owncloud/android/lib/resources/e2ee/UpdateMetadataRemoteOperationTest.java
  src/main/java/com/owncloud/android/lib/resources/status/GetCapabilitiesRemoteOperation.java
  src/main/java/com/owncloud/android/lib/resources/status/OwnCloudVersion.java
Labels: 3. to release

#472 Handling for share types ROOM/FEDERATED
  src/main/java/com/owncloud/android/lib/common/network/WebdavEntry.java
Labels: 2. to review, backport-request

#474 add public constructor for TrashbinFile (test only)
  src/main/java/com/owncloud/android/lib/resources/trashbin/model/TrashbinFile.java
Labels: 2. to review
