Repository nextcloud/android-library, pull requests merged in 2020-05, with the labels that each got.

#433 remove bug class: LSC_LITERAL_STRING_COMPARISON
  scripts/analysis/findbugs-results.txt
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/main/java/com/owncloud/android/lib/common/operations/ExceptionParser.java
  src/main/java/com/owncloud/android/lib/resources/files/DownloadFileRemoteOperation.java
  src/main/java/com/owncloud/android/lib/resources/files/model/FileVersion.java
  src/main/java/com/owncloud/android/lib/resources/shares/ShareXMLParser.java
  src/main/java/com/owncloud/android/lib/resources/trashbin/model/TrashbinFile.java
Labels: 2. to review

#422 Use e2e-token
  .drone.yml
  build.gradle
  scripts/analysis/findbugs-results.txt
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/androidTest/java/com/owncloud/android/lib/resources/e2ee/UpdateMetadataRemoteOperationTest.java
  src/androidTest/java/com/owncloud/android/lib/resources/files/SearchRemoteOperationTest.java
  src/main/java/com/owncloud/android/lib/common/operations/RemoteOperation.java
  src/main/java/com/owncloud/android/lib/resources/e2ee/LockFileRemoteOperation.java
  src/main/java/com/owncloud/android/lib/resources/e2ee/UnlockFileRemoteOperation.java
  src/main/java/com/owncloud/android/lib/resources/e2ee/UpdateMetadataRemoteOperation.java
  src/main/java/com/owncloud/android/lib/resources/files/ChunkedFileUploadRemoteOperation.java
  src/main/java/com/owncloud/android/lib/resources/files/CreateFolderRemoteOperation.java
  src/main/java/com/owncloud/android/lib/resources/files/UploadFileRemoteOperation.java
  src/main/java/com/owncloud/android/lib/resources/files/model/RemoteFile.java
  src/main/java/com/owncloud/android/lib/resources/files/model/ServerFileInterface.java
  src/main/java/com/owncloud/android/lib/resources/users/CheckRemoteWipeRemoteOperation.java
  src/main/java/com/owncloud/android/lib/resources/users/RemoteWipeSuccessRemoteOperation.java
Labels: 2. to review

#434 Enable etag for capabilities endpoint
  src/androidTest/java/com/owncloud/android/GetCapabilitiesTest.java
  src/main/java/com/owncloud/android/lib/common/operations/RemoteOperation.java
  src/main/java/com/owncloud/android/lib/resources/status/GetCapabilitiesRemoteOperation.java
  src/main/java/com/owncloud/android/lib/resources/status/OCCapability.java
Labels: 2. to review, enhancement

#436 Clarify download
  src/main/java/com/owncloud/android/lib/resources/files/DownloadFileRemoteOperation.java
Labels: 2. to review

#439 If we cancel by user, we pass a reason, so app can handle it correctly
  src/main/java/com/owncloud/android/lib/resources/files/ChunkedFileUploadRemoteOperation.java
  src/main/java/com/owncloud/android/lib/resources/files/UploadFileRemoteOperation.java
Labels: 2. to review, client change required

#441 run CI against stable / master
  .drone.yml
  scripts/uploadReport.sh
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/androidTest/java/com/owncloud/android/GetCapabilitiesTest.java
  src/androidTest/java/com/owncloud/android/RetryTestRule.kt
  src/androidTest/java/com/owncloud/android/lib/resources/e2ee/UpdateMetadataRemoteOperationTest.java
  src/androidTest/java/com/owncloud/android/lib/resources/shares/GetSharesRemoteOperationTest.java
  src/main/java/com/owncloud/android/lib/resources/status/GetCapabilitiesRemoteOperation.java
Labels: 2. to review
