Repository nextcloud/android-library, pull requests merged in 2021-12, with the labels that each got.

#773 OwnCloudClient: Do not encode @ in userIds
  src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
Labels: 2. to review, backport-request

#780 Enhance tests for master server
  src/androidTest/java/com/nextcloud/android/lib/resources/directediting/DirectEditingCreateFileRemoteOperationIT.java
  src/androidTest/java/com/nextcloud/android/lib/resources/directediting/DirectEditingObtainListOfTemplatesRemoteOperationIT.java
  src/androidTest/java/com/nextcloud/android/lib/resources/directediting/DirectEditingObtainRemoteOperationIT.java
  src/androidTest/java/com/nextcloud/android/lib/resources/directediting/DirectEditingOpenFileRemoteOperationIT.java
  src/androidTest/java/com/nextcloud/android/lib/resources/search/SearchProvidersRemoteOperationIT.kt
  src/androidTest/java/com/nextcloud/android/lib/resources/users/GenerateAppPasswordRemoteOperationIT.java
  src/androidTest/java/com/nextcloud/android/lib/richWorkspace/RichWorkspaceDirectEditingRemoteOperationIT.java
  src/androidTest/java/com/nextcloud/lib/resources/users/GetUserInfoRemoteOperationIT.kt
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/androidTest/java/com/owncloud/android/DeleteFileIT.java
  src/androidTest/java/com/owncloud/android/lib/common/operations/CreateShareIT.java
  src/androidTest/java/com/owncloud/android/lib/common/operations/GetSharesIT.java
  src/androidTest/java/com/owncloud/android/lib/common/operations/GetUserQuotaIT.java
  src/androidTest/java/com/owncloud/android/lib/common/operations/RemoveShareIT.java
  src/androidTest/java/com/owncloud/android/lib/resources/comments/CommentFileRemoteOperationIT.kt
  src/androidTest/java/com/owncloud/android/lib/resources/e2ee/UpdateMetadataRemoteOperationIT.java
  src/androidTest/java/com/owncloud/android/lib/resources/files/CheckEtagRemoteOperationIT.kt
  src/androidTest/java/com/owncloud/android/lib/resources/files/DownloadFileRemoteOperationIT.kt
  src/androidTest/java/com/owncloud/android/lib/resources/files/ExistenceCheckRemoteOperationIT.kt
  src/androidTest/java/com/owncloud/android/lib/resources/files/MoveFileRemoteOperationIT.kt
  src/androidTest/java/com/owncloud/android/lib/resources/files/ReadFileRemoteOperationIT.kt
  src/androidTest/java/com/owncloud/android/lib/resources/files/ReadFolderRemoteOperationIT.kt
  src/androidTest/java/com/owncloud/android/lib/resources/files/RenameFileRemoteOperationIT.kt
  src/androidTest/java/com/owncloud/android/lib/resources/files/SearchRemoteOperationIT.java
  src/androidTest/java/com/owncloud/android/lib/resources/shares/GetSharesRemoteOperationIT.java
  src/androidTest/java/com/owncloud/android/lib/resources/users/SetUserInfoRemoteOperationIT.java
  src/main/java/com/owncloud/android/lib/resources/users/Status.kt
Labels: 1. developing

#779 Bump compileSdkVersion to 31
  build.gradle
Labels: 2. to review
