Repository nextcloud/android-library, pull requests merged in 2022-01, with the labels that each got.

#791 Manually bump lib
  build.gradle
Labels: 2. to review

#794 Run analysis workflow in github actions instead of Drone
  .drone.yml
  .github/workflows/analysis.yml
  scripts/analysis/findbugs-up.rb
Labels: 2. to review

#796 Codecov: don't annotate diffs
  .codecov.yml
Labels: 2. to review

#792 OwnCloudClient: don't encode '+' in usernames
  src/androidTest/java/com/owncloud/android/lib/common/OwnCloudClientTest.kt
  src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
Labels: 1. developing

#793 IPv4 fallback when IPv6 is not available
  src/main/java/com/nextcloud/common/DNSCache.kt
  src/main/java/com/nextcloud/common/IPV6PreferringDNS.java
  src/main/java/com/nextcloud/common/IPV6PreferringDNS.kt
  src/main/java/com/nextcloud/common/IPv4FallbackInterceptor.kt
  src/main/java/com/nextcloud/common/NextcloudClient.kt
  src/main/java/com/nextcloud/common/PlainClient.kt
  src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
  src/main/java/com/owncloud/android/lib/common/OwnCloudClientFactory.java
  src/main/java/com/owncloud/android/lib/common/network/AdvancedSslSocketFactory.java
  src/test/java/com/nextcloud/common/DNSCacheTest.kt
Labels: 2. to review

#782 allow to query photos and videos also from external storages in gallery
  scripts/analysis/findbugs-results.txt
  src/androidTest/java/com/owncloud/android/lib/resources/files/SearchRemoteOperationIT.java
  src/main/java/com/owncloud/android/lib/resources/files/NcSearchMethod.java
  src/main/java/com/owncloud/android/lib/resources/files/SearchRemoteOperation.java
  src/main/java/com/owncloud/android/lib/resources/status/NextcloudVersion.kt
Labels: enhancement, 2. to review, client change required

#798 Bump script branches for stable-2.9
  scripts/analysis/analysis-wrapper.sh
  scripts/analysis/getBranchName.sh
Labels: 2. to review

#800 Workflows: use Eclipse Temurin instead of AdoptOpenJDK
  .github/workflows/analysis.yml
  .github/workflows/detekt.yml
  .github/workflows/ktlint.yml
  .github/workflows/lint.yml
Labels: 2. to review

#803 Run analysis workflow on push
  .github/workflows/analysis.yml
Labels: 2. to review, backport-request

#806 analysis: Fix checkout and commit generation
  .github/workflows/analysis.yml
  scripts/analysis/findbugs-up.rb
Labels: 2. to review

#807 [stable-2.9] analysis: Fix checkout and commit generation
  .github/workflows/analysis.yml
  scripts/analysis/findbugs-up.rb
Labels: 2. to review
