Repository nextcloud/android-library, pull requests merged in 2022-03, with the labels that each got.

#827 Rely on external creation timestamp
  src/androidTest/java/com/owncloud/android/lib/resources/files/UploadFileRemoteOperationIT.kt
  src/main/java/com/owncloud/android/lib/resources/files/ChunkedFileUploadRemoteOperation.java
  src/main/java/com/owncloud/android/lib/resources/files/UploadFileRemoteOperation.java
Labels: 1. developing, client change required

#831 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#832 Dependabot: check github actions updates
  .github/dependabot.yml
Labels: 2. to review

#837 Test against latest stable
  .drone.yml
Labels: 2. to review

#838 Update analysis workflow from app
  .github/workflows/analysis.yml
  scripts/analysis/findbugs-up.rb
Labels: 2. to review

#839 Have userId tests also for NextcloudClient
  src/androidTest/java/com/owncloud/android/lib/common/OwnCloudClientTest.kt
  src/main/java/com/nextcloud/common/NextcloudClient.kt
  src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
Labels: 1. developing

#840 Use ktlint plugin instead of manual config
  .github/workflows/check.yml
  .github/workflows/detekt.yml
  .github/workflows/ktlint.yml
  .github/workflows/lint.yml
  build.gradle
  scripts/hooks/pre-commit
Labels: 2. to review

#846 DNSCache: add TTL of 30 seconds to cache entries
  library/.gitignore
  library/src/main/java/com/nextcloud/android/lib/core/Clock.kt
  library/src/main/java/com/nextcloud/android/lib/core/ClockImpl.kt
  library/src/main/java/com/nextcloud/common/DNSCache.kt
  library/src/test/java/com/nextcloud/common/ClockStub.kt
  library/src/test/java/com/nextcloud/common/DNSCacheTest.kt
Labels: 2. to review, backport-request
