Repository nextcloud/android-library, pull requests merged in 2022-04, with the labels that each got.

#844 Parse more attributes for shares
  library/src/androidTest/java/com/owncloud/android/lib/resources/shares/GetSharesRemoteOperationIT.java
  library/src/main/java/com/owncloud/android/lib/resources/files/SearchRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/shares/OCShare.java
  library/src/main/java/com/owncloud/android/lib/resources/shares/ShareXMLParser.java
Labels: 2. to review

#850 Retrieve permission when doing a gallery search
  library/src/main/java/com/owncloud/android/lib/resources/files/NcSearchMethod.java
Labels: 2. to review

#854 Encode single quotes in usernames
  library/src/androidTest/java/com/owncloud/android/lib/common/OwnCloudClientTest.kt
  library/src/main/java/com/nextcloud/common/NextcloudClient.kt
  library/src/main/java/com/nextcloud/common/UserIdEncoder.kt
  library/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
Labels: 2. to review, backport-request

#873 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#874 Add test for https://github.com/nextcloud/android-library/pull/870
  library/src/androidTest/java/com/owncloud/android/lib/resources/files/UploadFileRemoteOperationIT.kt
  library/src/main/java/com/owncloud/android/lib/resources/files/UploadFileRemoteOperation.java
Labels: 2. to review
