Repository nextcloud/android-library, pull requests merged in 2022-05, with the labels that each got.

#851 File locking
  .drone.yml
  library/detekt.yml
  library/src/androidTest/java/com/nextcloud/android/lib/resources/files/ToggleFileLockRemoteOperationIT.kt
  library/src/androidTest/java/com/owncloud/android/AbstractIT.java
  library/src/androidTest/java/com/owncloud/android/GetCapabilitiesIT.java
  library/src/main/java/com/nextcloud/android/lib/resources/files/ToggleFileLockRemoteOperation.kt
  library/src/main/java/com/nextcloud/common/NextcloudClient.kt
  library/src/main/java/com/nextcloud/common/NextcloudUriDelegate.kt
  library/src/main/java/com/nextcloud/common/NextcloudUriProvider.kt
  library/src/main/java/com/nextcloud/operations/LockMethod.kt
  library/src/main/java/com/nextcloud/operations/UnlockMethod.kt
  library/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
  library/src/main/java/com/owncloud/android/lib/common/network/WebdavEntry.java
  library/src/main/java/com/owncloud/android/lib/common/network/WebdavUtils.java
  library/src/main/java/com/owncloud/android/lib/common/utils/WebDavFileUtils.java
  library/src/main/java/com/owncloud/android/lib/resources/files/ReadFolderRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/files/model/FileLockType.kt
  library/src/main/java/com/owncloud/android/lib/resources/files/model/RemoteFile.java
  library/src/main/java/com/owncloud/android/lib/resources/status/CapabilityBooleanType.kt
  library/src/main/java/com/owncloud/android/lib/resources/status/GetCapabilitiesRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/status/NextcloudVersion.kt
  library/src/main/java/com/owncloud/android/lib/resources/status/OCCapability.java
  library/src/main/java/com/owncloud/android/lib/resources/status/OCCapability.kt
  library/src/main/java/com/owncloud/android/lib/resources/users/SetUserInfoRemoteOperation.java
  library/src/test/java/com/owncloud/android/lib/common/network/WebdavEntryTest.kt
  scripts/analysis/findbugs-results.txt
Labels: 2. to review

#878 build: More repo cleanup
  build.gradle
Labels: 2. to review, backport-request

#882 drone: Use master branch for files_lock
  .drone.yml
Labels: 2. to review, backport-request

#883 [stable-2.10] File locking
  .drone.yml
  library/detekt.yml
  library/src/androidTest/java/com/nextcloud/android/lib/resources/files/ToggleFileLockRemoteOperationIT.kt
  library/src/androidTest/java/com/owncloud/android/AbstractIT.java
  library/src/androidTest/java/com/owncloud/android/GetCapabilitiesIT.java
  library/src/main/java/com/nextcloud/android/lib/resources/files/ToggleFileLockRemoteOperation.kt
  library/src/main/java/com/nextcloud/common/NextcloudClient.kt
  library/src/main/java/com/nextcloud/common/NextcloudUriDelegate.kt
  library/src/main/java/com/nextcloud/common/NextcloudUriProvider.kt
  library/src/main/java/com/nextcloud/operations/LockMethod.kt
  library/src/main/java/com/nextcloud/operations/UnlockMethod.kt
  library/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
  library/src/main/java/com/owncloud/android/lib/common/network/WebdavEntry.java
  library/src/main/java/com/owncloud/android/lib/common/network/WebdavUtils.java
  library/src/main/java/com/owncloud/android/lib/common/utils/WebDavFileUtils.java
  library/src/main/java/com/owncloud/android/lib/resources/files/ReadFolderRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/files/model/FileLockType.kt
  library/src/main/java/com/owncloud/android/lib/resources/files/model/RemoteFile.java
  library/src/main/java/com/owncloud/android/lib/resources/status/CapabilityBooleanType.kt
  library/src/main/java/com/owncloud/android/lib/resources/status/GetCapabilitiesRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/status/NextcloudVersion.kt
  library/src/main/java/com/owncloud/android/lib/resources/status/OCCapability.java
  library/src/main/java/com/owncloud/android/lib/resources/status/OCCapability.kt
  library/src/main/java/com/owncloud/android/lib/resources/users/SetUserInfoRemoteOperation.java
  library/src/test/java/com/owncloud/android/lib/common/network/WebdavEntryTest.kt
  scripts/analysis/findbugs-results.txt
Labels: 2. to review

#887 Restore userID encoding when building files DAV uri
  .drone.yml
  library/src/androidTest/java/com/owncloud/android/lib/common/UsernameVariationsIT.kt
  library/src/main/java/com/nextcloud/common/NextcloudClient.kt
  library/src/main/java/com/nextcloud/common/NextcloudUriDelegate.kt
  library/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
Labels: 2. to review, backport-request

#886 OCCapability: restore nullability of optional strings
  library/src/main/java/com/owncloud/android/lib/resources/status/OCCapability.kt
  library/src/test/java/com/owncloud/android/lib/resources/status/OCCapabilityTest.kt
Labels: 2. to review, backport-request

#891 OCCapability: more nullability fixes
  library/src/main/java/com/owncloud/android/lib/resources/status/OCCapability.kt
  library/src/test/java/com/owncloud/android/lib/resources/status/OCCapabilityTest.kt
Labels: 2. to review, backport-request

#894 Jetifier not needed any longer
  gradle.properties
Labels: 2. to review

#897 Bump okhttp to 5.0.0-alpha7 for Happy Eyeballs support
  library/build.gradle
  library/src/main/java/com/nextcloud/common/IPV6PreferringDNS.kt
  library/src/main/java/com/nextcloud/common/IPv4FallbackInterceptor.kt
  library/src/main/java/com/nextcloud/common/NextcloudClient.kt
  library/src/main/java/com/nextcloud/common/PlainClient.kt
Labels: 2. to review

#898 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies
