Repository nextcloud/android-library, pull requests merged in 2022-10, with the labels that each got.

#975 external app needs composer
  .drone.yml
Labels: 2. to review

#942 Test: share a file, favorite it and search then for favorites
  library/src/androidTest/java/com/owncloud/android/AbstractIT.java
  library/src/androidTest/java/com/owncloud/android/lib/resources/files/SearchRemoteOperationIT.java
Labels: 1. developing

#983 OkHttpMethodBase: prevent NPE when logging exception
  library/src/main/java/com/nextcloud/common/OkHttpMethodBase.kt
Labels: 2. to review, backport-request
