Repository nextcloud/android-library, pull requests merged in 2023-05, with the labels that each got.

#1113 fix spotbugs
  library/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
  library/src/main/java/com/owncloud/android/lib/common/OwnCloudClientManager.java
  library/src/main/java/com/owncloud/android/lib/common/network/AdvancedSslSocketFactory.java
  library/src/main/java/com/owncloud/android/lib/common/network/AdvancedX509TrustManager.java
  library/src/main/java/com/owncloud/android/lib/common/network/WebdavEntry.java
  library/src/main/java/com/owncloud/android/lib/resources/files/FileUtils.java
  scripts/analysis/findbugs-results.txt
Labels: 3. to review

#1109 Support to read Groupfolders
  .drone.yml
  library/src/androidTest/java/com/nextcloud/android/lib/resources/groupfolders/GetGroupfoldersRemoteOperationIT.kt
  library/src/androidTest/java/com/owncloud/android/AbstractIT.java
  library/src/androidTest/java/com/owncloud/android/GetCapabilitiesIT.java
  library/src/androidTest/java/com/owncloud/android/lib/resources/files/ReadFolderRemoteOperationIT.kt
  library/src/androidTest/java/com/owncloud/android/lib/resources/files/SearchRemoteOperationIT.java
  library/src/main/java/com/nextcloud/android/lib/resources/groupfolders/GetGroupfoldersRemoteOperation.kt
  library/src/main/java/com/nextcloud/android/lib/resources/groupfolders/Groupfolder.kt
  library/src/main/java/com/owncloud/android/lib/resources/status/GetCapabilitiesRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/status/OCCapability.kt
Labels: 3. to review

#1082 Delombok some more classes
  library/build.gradle
  library/src/androidTest/java/com/owncloud/android/lib/resources/shares/ShareXMLParserIT.kt
  library/src/main/java/com/owncloud/android/lib/common/network/WebdavEntry.java
  library/src/main/java/com/owncloud/android/lib/common/network/WebdavEntry.kt
  library/src/main/java/com/owncloud/android/lib/ocs/OCSMeta.java
  library/src/main/java/com/owncloud/android/lib/ocs/OCSResponse.java
  library/src/main/java/com/owncloud/android/lib/ocs/ServerResponse.java
  library/src/main/java/com/owncloud/android/lib/resources/files/model/RemoteFile.java
  library/src/main/java/com/owncloud/android/lib/resources/files/model/RemoteFile.kt
  library/src/main/java/com/owncloud/android/lib/resources/notifications/models/Notification.java
  library/src/main/java/com/owncloud/android/lib/resources/shares/OCShare.java
  library/src/main/java/com/owncloud/android/lib/resources/shares/OCShare.kt
  library/src/main/java/com/owncloud/android/lib/resources/status/OwnCloudVersion.java
  library/src/main/java/com/owncloud/android/lib/resources/tags/GetTagsRemoteOperation.kt
  library/src/main/java/com/owncloud/android/lib/resources/trashbin/model/TrashbinFile.java
  scripts/analysis/findbugs-results.txt
Labels: 3. to review, client change required, technical debt

#1059 Trashbin update
  library/src/androidTest/java/com/owncloud/android/lib/resources/trashbin/ReadTrashbinFolderRemoteOperationIT.kt
  library/src/main/java/com/owncloud/android/lib/resources/trashbin/EmptyTrashbinRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/trashbin/ReadTrashbinFolderRemoteOperation.java
Labels: 3. to review, client change required

#1137 chore: update workflows from templates
  .github/workflows/command-rebase.yml
Labels: 3. to review, dependencies, automated
