Repository nextcloud/android-library, pull requests merged in 2023-01, with the labels that each got.

#959 Add RemoteOperation to delete encryption keys
  library/src/main/java/com/owncloud/android/lib/resources/users/DeletePrivateKeyOperation.kt
  library/src/main/java/com/owncloud/android/lib/resources/users/GetPublicKeyOperation.java
Labels: 2. to review, client change required

#1027 fix findings of detekt
  library/detekt.yml
  library/src/androidTest/java/com/nextcloud/common/NextcloudUriDelegateIT.kt
  library/src/androidTest/java/com/owncloud/android/lib/resources/shares/ShareXMLParserIT.kt
  library/src/main/java/com/nextcloud/common/NextcloudClient.kt
  library/src/main/java/com/nextcloud/common/OkHttpMethodBase.kt
Labels: 2. to review

#1037 fix hover card test
  library/src/androidTest/java/com/nextcloud/android/lib/resources/profile/GetHoverCardRemoteOperationIT.kt
Labels: 2. developing

#1039 Increase wait time for `wait_for_server`
  scripts/wait_for_server.sh
Labels: 3. to review

#1040 files_lock uses now main branch name
  .drone.yml
Labels: 3. to review

#1036 Workflows: disable automerge for dependabot PRs
  .github/workflows/autoApproveDependabot.yml
Labels: 3. to review

#1041 drone: Fix branch name for text app
  .drone.yml
Labels: 3. to review

#651 Retrieve localId via webdav
  library/src/androidTest/java/com/nextcloud/android/lib/resources/search/UnifiedSearchRemoteOperationIT.kt
  library/src/androidTest/java/com/owncloud/android/FileIT.java
  library/src/androidTest/java/com/owncloud/android/lib/resources/files/SearchRemoteOperationIT.java
  library/src/main/java/com/nextcloud/common/NextcloudUriDelegate.kt
  library/src/main/java/com/nextcloud/common/NextcloudUriProvider.kt
  library/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
  library/src/main/java/com/owncloud/android/lib/common/network/WebdavEntry.java
  library/src/main/java/com/owncloud/android/lib/common/network/WebdavUtils.java
  library/src/main/java/com/owncloud/android/lib/resources/activities/GetActivitiesRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/comments/CommentFileRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/comments/MarkCommentsAsReadRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/e2ee/GetMetadataRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/e2ee/LockFileRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/e2ee/StoreMetadataRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/e2ee/ToggleEncryptionRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/e2ee/UnlockFileRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/e2ee/UpdateMetadataRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/files/ReadFileVersionsRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/files/RestoreFileVersionRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/files/model/FileVersion.java
  library/src/main/java/com/owncloud/android/lib/resources/files/model/RemoteFile.java
  library/src/main/java/com/owncloud/android/lib/resources/files/model/ServerFileInterface.java
  library/src/main/java/com/owncloud/android/lib/resources/trashbin/model/TrashbinFile.java
Labels: 3. to review, client change required

#1043 build: Bump compileSdk to 33
  library/build.gradle
Labels: 3. to review

#1009 use qualified assert import
  library/src/androidTest/java/com/nextcloud/android/lib/resources/profile/GetHoverCardRemoteOperationIT.kt
  library/src/androidTest/java/com/nextcloud/android/lib/resources/search/SearchProvidersRemoteOperationIT.kt
  library/src/androidTest/java/com/nextcloud/common/NextcloudUriDelegateIT.kt
  library/src/androidTest/java/com/owncloud/android/AbstractIT.java
  library/src/androidTest/java/com/owncloud/android/ExceptionParserIT.java
  library/src/androidTest/java/com/owncloud/android/PlainClientIT.kt
  library/src/androidTest/java/com/owncloud/android/lib/common/OwnCloudAccountTest.java
  library/src/androidTest/java/com/owncloud/android/lib/common/OwnCloudBasicCredentialsTest.java
  library/src/androidTest/java/com/owncloud/android/lib/common/UsernameVariationsIT.kt
  library/src/androidTest/java/com/owncloud/android/lib/resources/shares/GetSharesRemoteOperationIT.java
  library/src/androidTest/java/com/owncloud/android/lib/resources/shares/UpdateShareRemoteOperationIT.kt
  library/src/androidTest/java/com/owncloud/android/lib/resources/status/OwnCloudVersionTest.java
  library/src/test/java/com/nextcloud/common/DNSCacheTest.kt
  library/src/test/java/com/owncloud/android/lib/common/network/WebdavEntryTest.kt
  library/src/test/java/com/owncloud/android/lib/common/operations/RemoteOperationResultTest.kt
  library/src/test/java/com/owncloud/android/lib/resources/files/FileUtilsTest.java
Labels: 3. to review
