Repository nextcloud/android-library, pull requests merged in 2024-06, with the labels that each got.

#1464 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#1271 Deprecate OwncloudClient - Helpers
  library/src/main/java/com/nextcloud/common/JSONRequestBody.kt
  library/src/main/java/com/nextcloud/operations/HeadMethod.kt
Labels: 3. to review, feedback-requested

#1272 Deprecate OwncloudClient - Notifications
  gradle/verification-metadata.xml
  library/src/androidTest/java/com/owncloud/android/lib/resources/notifications/NotificationIT.kt
  library/src/androidTest/java/com/owncloud/android/lib/resources/users/StatusIT.kt
  library/src/main/java/com/owncloud/android/lib/resources/notifications/DeleteAllNotificationsRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/notifications/DeleteNotificationRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/notifications/GetNotificationRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/notifications/GetNotificationsRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/notifications/RegisterAccountDeviceForNotificationsOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/notifications/RegisterAccountDeviceForProxyOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/notifications/UnregisterAccountDeviceForNotificationsOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/notifications/UnregisterAccountDeviceForProxyOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/users/SetPredefinedCustomStatusMessageRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/users/SetStatusRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/users/SetUserDefinedCustomStatusMessageRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/users/SetUserInfoRemoteOperation.java
Labels: 3. to review, feedback-requested

#1273 Deprecate OwncloudClient - DirectEditing
  library/src/androidTest/java/com/nextcloud/android/lib/resources/directediting/DirectEditingCreateFileRemoteOperationIT.java
  library/src/androidTest/java/com/nextcloud/android/lib/resources/directediting/DirectEditingObtainListOfTemplatesRemoteOperationIT.java
  library/src/androidTest/java/com/nextcloud/android/lib/resources/directediting/DirectEditingObtainRemoteOperationIT.kt
  library/src/androidTest/java/com/nextcloud/android/lib/resources/directediting/DirectEditingOpenFileRemoteOperationIT.java
  library/src/main/java/com/nextcloud/android/lib/resources/directediting/DirectEditingCreateFileRemoteOperation.java
  library/src/main/java/com/nextcloud/android/lib/resources/directediting/DirectEditingObtainListOfTemplatesRemoteOperation.java
  library/src/main/java/com/nextcloud/android/lib/resources/directediting/DirectEditingObtainRemoteOperation.java
  library/src/main/java/com/nextcloud/android/lib/resources/directediting/DirectEditingOpenFileRemoteOperation.java
Labels: 3. to review, feedback-requested

#1295 Deprecate OwncloudClient - Comments
  library/src/androidTest/java/com/owncloud/android/lib/resources/comments/CommentFileRemoteOperationIT.kt
  library/src/main/java/com/owncloud/android/lib/resources/comments/CommentFileRemoteOperation.java
Labels: 3. to review, feedback-requested

#1470 new min server is NC17
  library/src/main/java/com/owncloud/android/lib/resources/status/OwnCloudVersion.java
  library/src/test/java/com/owncloud/android/lib/resources/status/OwnCloudVersionTest.java
Labels: 3. to review

#1477 Bug-fix Check ownCloudClient nullability in NextcloudClient
  library/src/main/java/com/nextcloud/common/NextcloudClient.kt
Labels: 3. to review

#1484 Test stable29
  .drone.yml
  scripts/uploadReport.sh
Labels: 2. developing
