Repository nextcloud/android-library, pull requests merged in 2024-04, with the labels that each got.

#1414 Add SPDX header template
  .idea/copyright/Nextcloud_Android_Library.xml
  .idea/copyright/profiles_settings.xml
Labels: 4. to release, technical debt

#1437 New versions
  library/src/main/java/com/owncloud/android/lib/resources/status/NextcloudVersion.kt
Labels: 3. to review

#1443 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#1442 Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
