Repository nextcloud/android-library, pull requests merged in 2024-11, with the labels that each got.

#1580 fix(translation): Backport transifex config
  .tx/config
  .tx/config.license
Labels: backport-request

#1575 bump to sdk35
  library/build.gradle
  sample_client/build.gradle
Labels: 3. to review

#1576 minSDK 19 to support libs
  library/build.gradle
  library/src/main/java/com/nextcloud/common/OkHttpCredentialsUtil.kt
  library/src/main/java/com/owncloud/android/lib/common/OwnCloudAnonymousCredentials.java
  library/src/main/java/com/owncloud/android/lib/common/OwnCloudBasicCredentials.java
  library/src/main/java/com/owncloud/android/lib/common/OwnCloudClientFactory.java
  sample_client/build.gradle
Labels: 3. to review

#1592 fix failing CI
  .drone.yml
Labels: 2. developing

#1485 base url shall never be null
  library/src/main/java/com/nextcloud/common/NextcloudUriDelegate.kt
  library/src/main/java/com/nextcloud/common/NextcloudUriProvider.kt
Labels: 3. to review
