Repository nextcloud/android-library, pull requests merged in 2024-03, with the labels that each got.

#1363 Assistant Endpoints
  .drone.yml
  library/src/androidTest/java/com/owncloud/android/lib/resources/assistant/AssistantIT.kt
  library/src/main/java/com/owncloud/android/lib/common/operations/RemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/OCSRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/assistant/CreateTaskRemoteOperation.kt
  library/src/main/java/com/owncloud/android/lib/resources/assistant/DeleteTaskRemoteOperation.kt
  library/src/main/java/com/owncloud/android/lib/resources/assistant/GetTaskListRemoteOperation.kt
  library/src/main/java/com/owncloud/android/lib/resources/assistant/GetTaskTypesRemoteOperation.kt
  library/src/main/java/com/owncloud/android/lib/resources/assistant/model/TaskList.kt
  library/src/main/java/com/owncloud/android/lib/resources/assistant/model/TaskTypes.kt
  scripts/uploadReport.sh
Labels: 3. to review

#1385 Add Assistant Capability
  library/src/androidTest/java/com/owncloud/android/AbstractIT.java
  library/src/androidTest/java/com/owncloud/android/GetCapabilitiesRemoteOperationIT.java
  library/src/main/java/com/owncloud/android/lib/resources/status/GetCapabilitiesRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/status/OCCapability.kt
Labels: 3. to review

#1386 Add reuse compliance badge
  README.md
Labels: 4. to release

#1387 Bugfix Delete Cached Nextcloud Client For Account Removal
  library/src/main/java/com/owncloud/android/lib/common/OwnCloudClientManager.java
Labels: 3. to review, backport-request

#1395 Remove duplicate license definitions
  .reuse/dep5
  gradlew
  gradlew.bat
Labels: 3. to review

#1289 Check Nullability of OCS Remote Operation
  library/src/main/java/com/nextcloud/android/lib/resources/dashboard/DashboardGetWidgetItemsRemoteOperation.kt
  library/src/main/java/com/nextcloud/android/lib/resources/dashboard/DashboardListWidgetsRemoteOperation.kt
  library/src/main/java/com/nextcloud/android/lib/resources/directediting/DirectEditingObtainListOfTemplatesRemoteOperation.java
  library/src/main/java/com/nextcloud/android/lib/resources/directediting/DirectEditingObtainRemoteOperation.java
  library/src/main/java/com/nextcloud/android/lib/resources/groupfolders/GetGroupfoldersRemoteOperation.kt
  library/src/main/java/com/nextcloud/android/lib/resources/profile/GetHoverCardRemoteOperation.kt
  library/src/main/java/com/owncloud/android/lib/resources/OCSRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/OCSRemoteOperation.kt
  library/src/main/java/com/owncloud/android/lib/resources/assistant/GetTaskListRemoteOperation.kt
  library/src/main/java/com/owncloud/android/lib/resources/assistant/GetTaskTypesRemoteOperation.kt
  library/src/main/java/com/owncloud/android/lib/resources/users/ConvertAppTokenRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/users/GetPredefinedStatusesRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/users/GetPrivateKeyRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/users/GetStatusRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/users/GetUserInfoRemoteOperation.java
Labels: bug, 3. to review

#1349 Bugfix Cover Missing GPS and Photo Size
  library/src/androidTest/java/com/nextcloud/extensions/DavPropertyProcessorTest.kt
  library/src/androidTest/java/com/nextcloud/extensions/ElementCreator.kt
  library/src/androidTest/java/com/nextcloud/extensions/XmlDataProcessorTest.kt
  library/src/main/java/com/nextcloud/extensions/ArrayListExtensions.kt
  library/src/main/java/com/nextcloud/extensions/GsonExtensions.kt
  library/src/main/java/com/owncloud/android/lib/common/network/WebdavEntry.kt
Labels: 3. to review, backport-request

#1410 Run also on stable branch
  .drone.yml
Labels: backport-request
