Repository nextcloud/android-library, pull requests merged in 2024-01, with the labels that each got.

#1187 E2E sharing
  .drone.yml
  .idea/codeStyles/Project.xml
  library/build.gradle
  library/lint.xml
  library/src/androidTest/java/com/owncloud/android/GetCapabilitiesRemoteOperationIT.java
  library/src/androidTest/java/com/owncloud/android/lib/resources/e2ee/SendCSRRemoteOperationIT.kt
  library/src/androidTest/java/com/owncloud/android/lib/resources/e2ee/UpdateMetadataRemoteOperationIT.java
  library/src/main/java/com/nextcloud/common/OkHttpMethodBase.kt
  library/src/main/java/com/owncloud/android/lib/resources/e2ee/CsrHelper.kt
  library/src/main/java/com/owncloud/android/lib/resources/e2ee/GetMetadataRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/e2ee/LockFileRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/e2ee/MetadataResponse.kt
  library/src/main/java/com/owncloud/android/lib/resources/e2ee/StoreMetadataRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/e2ee/StoreMetadataV2RemoteOperation.kt
  library/src/main/java/com/owncloud/android/lib/resources/e2ee/ToggleEncryptionRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/e2ee/UnlockFileRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/e2ee/UnlockFileV1RemoteOperation.kt
  library/src/main/java/com/owncloud/android/lib/resources/e2ee/UpdateMetadataRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/e2ee/UpdateMetadataV2RemoteOperation.kt
  library/src/main/java/com/owncloud/android/lib/resources/shares/GetShareesRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/shares/GetSharesRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/status/E2EVersion.kt
  library/src/main/java/com/owncloud/android/lib/resources/status/GetCapabilitiesRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/status/OCCapability.kt
  library/src/main/java/com/owncloud/android/lib/resources/users/DeletePrivateKeyRemoteOperation.kt
  library/src/main/java/com/owncloud/android/lib/resources/users/DeletePublicKeyRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/users/GetPrivateKeyRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/users/GetPublicKeyRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/users/SendCSRRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/users/StorePrivateKeyOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/users/StorePrivateKeyRemoteOperation.java
  sample_client/build.gradle
Labels: 3. to review, backport-request

#1308 Client cert
  library/src/main/AndroidManifest.xml
  library/src/main/java/com/nextcloud/common/NextcloudClient.kt
  library/src/main/java/com/nextcloud/common/PlainClient.kt
  library/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
  library/src/main/java/com/owncloud/android/lib/common/OwnCloudClientFactory.java
  library/src/main/java/com/owncloud/android/lib/common/network/AdvancedX509KeyManager.java
  library/src/main/java/com/owncloud/android/lib/common/network/AdvancedX509TrustManager.java
  library/src/main/java/com/owncloud/android/lib/common/network/NetworkUtils.java
  library/src/main/java/com/owncloud/android/lib/common/network/SelectClientCertificateHelperActivity.java
  library/src/main/res/values/strings.xml
  library/src/test/java/com/nextcloud/common/NextcloudClientTest.kt
  library/src/test/java/com/nextcloud/common/OkHttpMethodBaseTest.kt
  library/src/test/java/com/owncloud/android/lib/common/network/AdvancedX509KeyManagerTests.kt
Labels: 3. to review

#1335 add kotlin build configuration to groovy build configuration
  README.md
Labels: 4. to release

#1336 Add dependency checksums and signing key information
  .gitignore
  gradle.properties
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
Labels: 2. developing
