Repository nextcloud/android-library, pull requests merged in 2025-01, with the labels that each got.

#1205 test wipe check
  library/src/androidTest/java/com/nextcloud/android/lib/resources/users/GenerateAppPasswordRemoteOperationIT.java
  library/src/androidTest/java/com/owncloud/android/lib/resources/users/CheckRemoteWipeRemoteOperationIT.kt
  library/src/main/java/com/nextcloud/android/lib/resources/users/GenerateAppPasswordRemoteOperation.java
Labels: 3. to review

#1621 Migrate Gradle action
  .github/workflows/assemble.yml
Labels: 3. to review, github_actions, technical debt

#1624 BugFix - TaskProcessingAPI
  library/src/androidTest/java/com/owncloud/android/lib/resources/assistant/v2/AssistantV2Tests.kt
  library/src/main/java/com/owncloud/android/lib/resources/assistant/v2/GetTaskTypesRemoteOperationV2.kt
  library/src/main/java/com/owncloud/android/lib/resources/assistant/v2/model/TaskTypes.kt
Labels: 3. to review

#1605 retrieve recommendations
  .drone.yml
  library/src/androidTest/java/com/nextcloud/android/lib/resources/recommendations/GetRecommendationsRemoteOperationIT.kt
  library/src/androidTest/java/com/owncloud/android/GetCapabilitiesRemoteOperationIT.java
  library/src/main/java/com/nextcloud/android/lib/resources/recommendations/GetRecommendationsRemoteOperation.kt
  library/src/main/java/com/nextcloud/android/lib/resources/recommendations/Recommendation.kt
  library/src/main/java/com/nextcloud/android/lib/resources/recommendations/RecommendationResponse.kt
  library/src/main/java/com/owncloud/android/lib/resources/status/GetCapabilitiesRemoteOperation.java
  library/src/main/java/com/owncloud/android/lib/resources/status/NextcloudVersion.kt
  library/src/main/java/com/owncloud/android/lib/resources/status/OCCapability.kt
Labels: 3. to review

#1646 quota: unlimited space is now -3 instead of actual free space
  library/src/androidTest/java/com/owncloud/android/lib/common/operations/GetUserQuotaIT.java
Labels: 3. to review

#1645 Bump minimum required server version
  library/src/main/java/com/owncloud/android/lib/resources/status/OwnCloudVersion.java
  library/src/test/java/com/owncloud/android/lib/resources/status/OwnCloudVersionTest.java
Labels: 3. to review, client change required
