Repository nextcloud/android-library, pull requests merged in 2025-06, with the labels that each got.

#1713 BugFix - XML Exception Parser
  library/src/androidTest/java/com/owncloud/android/ExceptionParserIT.java
  library/src/androidTest/java/com/owncloud/android/ResponseFormatDetectorTests.kt
  library/src/androidTest/java/com/owncloud/android/XMLExceptionParserTests.kt
  library/src/main/java/com/owncloud/android/lib/common/operations/RemoteOperationResult.java
  library/src/main/java/com/owncloud/android/lib/common/operations/XMLExceptionParser.java
  library/src/main/java/com/owncloud/android/lib/common/utils/responseFormat/ResponseFormat.kt
  library/src/main/java/com/owncloud/android/lib/common/utils/responseFormat/ResponseFormatDetector.kt
Labels: 3. to review

#1724 Fixing a data transfer error
  library/src/main/java/com/owncloud/android/lib/common/network/ChunkFromFileChannelRequestEntity.java
Labels: bug, 3. to review, feedback-requested

#1754 ci: update reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
