Repository nextcloud/android-library, pull requests merged in 2025-07, with the labels that each got.

#1739 Add federated groups
  library/src/main/java/com/owncloud/android/lib/common/network/WebdavEntry.kt
  library/src/main/java/com/owncloud/android/lib/resources/shares/GetShareesRemoteOperation.java
Labels: enhancement, 3. to review, feedback-requested

#1758 Remove share attributes & use OCShare extensions
  library/src/androidTest/java/com/owncloud/android/lib/resources/shares/CreateShareRemoteOperationIT.kt
  library/src/main/java/com/owncloud/android/lib/resources/shares/attributes/ShareAttributes.kt
  library/src/main/java/com/owncloud/android/lib/resources/shares/attributes/ShareAttributesDeserializer.kt
  library/src/main/java/com/owncloud/android/lib/resources/shares/attributes/ShareAttributesJsonHandler.kt
  library/src/main/java/com/owncloud/android/lib/resources/shares/extensions/OCShareExtensions.kt
Labels: 3. to review

#1770 BugFix - DNSCache Lock
  library/src/main/java/com/nextcloud/common/DNSCache.kt
Labels: 3. to review, backport-request, Performance

#1721 Fix - AbstractIT
  library/src/androidTest/java/com/owncloud/android/AbstractIT.java
Labels: 3. to review

#1741 BugFix - Do not Filter Share Type
  library/src/androidTest/java/com/owncloud/android/FileIT.java
  library/src/main/java/com/owncloud/android/lib/common/network/WebdavEntry.kt
  library/src/main/java/com/owncloud/android/lib/resources/files/model/RemoteFile.kt
Labels: 3. to review, backport-request
